(()=>{
const D=window.VEILARIUM_DATA,$=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const art=id=>D.artworks[id];
const modeLabel=m=>({direct:'Direct depiction',contextual:'Contextual artwork',evocative:'Evocative artwork',literary:'Later literary reception',symbolic:'Symbolic / contextual'})[m]||m;
const tradition=id=>D.traditions.find(t=>t.id===id);
const fallbackArtFor=b=>art((tradition(b.cluster)||{}).artworkId||'e-nymphs');
function imageMarkup(a,cls='atlas-img',alt=''){return `<img class="${cls} atlas-img" src="${a.image}" data-original="${a.original}" alt="${alt||a.title}" loading="lazy" referrerpolicy="no-referrer">`}
function bindFallbacks(scope=document){$$('img.atlas-img',scope).forEach(img=>{if(img.dataset.bound)return;img.dataset.bound='1';img.onerror=()=>{if(img.dataset.original&&!img.dataset.tried){img.dataset.tried='1';img.src=img.dataset.original}else{img.onerror=null;img.classList.add('image-failed');img.removeAttribute('src')}}})}
function credit(a){return `${a.title} · ${a.artist} · ${a.date} · ${a.license}`}

// nav
$('#mobileMenu').onclick=()=>$('#siteNav').classList.toggle('open');$$('[data-jump]').forEach(x=>x.onclick=()=>document.getElementById(x.dataset.jump).scrollIntoView({behavior:'smooth'}));

// hero mosaic
const heroIds=['e-peri','e-kami','e-nymphs','e-devas','e-rusalka'];
$('#heroMosaic').innerHTML=heroIds.map(id=>{const a=art(id);return `<figure>${imageMarkup(a,'hero-tile')}<figcaption>${a.artist}</figcaption></figure>`}).join('');bindFallbacks($('#heroMosaic'));

// entity modal
const modal=$('#entityModal');
function openEntity(id){const b=D.beings.find(x=>x.id===id);if(!b)return;const a=art(b.artworkId),f=fallbackArtFor(b),img=$('#modalArt');img.src=a.image;img.dataset.original=a.original;img.dataset.tried='';img.alt=a.title;img.onerror=()=>{if(!img.dataset.tried){img.dataset.tried='1';img.src=a.original}else{img.onerror=null;img.src=f.image}};$('#modalArtCredit').textContent=credit(a)+(a.sfw?' · SFW-curated':'');$('#modalMode').textContent=modeLabel(a.mode);$('#modalMode').dataset.mode=a.mode;$('#modalKind').textContent=b.kind;$('#modalName').textContent=b.name;$('#modalMeta').textContent=`${b.tradition} · ${b.region}`;$('#modalSummary').textContent=b.summary;$('#modalSources').innerHTML=b.sources.map(s=>`<span>${s}</span>`).join('');$('#modalArtNote').textContent=a.note;$('#modalSourceLink').href=a.source;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}$('#modalClose').onclick=closeModal;modal.onclick=e=>{if(e.target===modal)closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
function randomEntity(){openEntity(D.beings[Math.floor(Math.random()*D.beings.length)].id)}$('#heroRandom').onclick=randomEntity;$('#portalRandom').onclick=randomEntity;$('#indexRandom').onclick=randomEntity;

// traditions
$('#traditionRail').innerHTML=D.traditions.map((t,i)=>`<button class="tradition-pill ${i?'':'active'}" data-trad="${t.id}">${t.name}</button>`).join('');
function entityTile(b){const a=art(b.artworkId);return `<button class="entity-tile" data-being="${b.id}"><div class="tile-art">${imageMarkup(a,'entity-img',a.title)}<span class="mode-mini">${modeLabel(a.mode)}</span></div><div class="tile-copy"><strong>${b.name}</strong><small>${b.kind}</small><em>${a.title}</em></div></button>`}
function renderChapter(id){$$('.tradition-pill').forEach(x=>x.classList.toggle('active',x.dataset.trad===id));const t=tradition(id),sig=art(t.artworkId),groups=D.traditionGroups[id]||[];$('#chapterStage').innerHTML=`<div class="chapter-intro"><div class="chapter-art">${imageMarkup(sig,'chapter-img',sig.title)}<div class="art-credit">${credit(sig)}</div></div><div class="chapter-copy"><div class="eyebrow">TRADITION CHAPTER</div><h3>${t.name}</h3><p class="chapter-sub">${t.subtitle}</p><p>${t.note}</p><a href="${sig.source}" target="_blank" rel="noopener" class="source-link">Signature artwork source ↗</a></div></div><div class="group-stack">${groups.map(g=>`<section class="entity-group"><div class="group-heading"><span>${g.title}</span><small>${g.ids.length} records</small></div><div class="entity-mosaic">${g.ids.map(eid=>entityTile(D.beings.find(b=>b.id===eid))).join('')}</div></section>`).join('')}</div>`;bindFallbacks($('#chapterStage'));$$('[data-being]',$('#chapterStage')).forEach(x=>x.onclick=()=>openEntity(x.dataset.being))}
$$('.tradition-pill').forEach(x=>x.onclick=()=>renderChapter(x.dataset.trad));renderChapter('south-asia');

// realms
$('#realmSystemRail').innerHTML=D.realmSystems.map((s,i)=>`<button class="tradition-pill ${i?'':'active'}" data-realm-system="${s.id}">${s.name}</button>`).join('');
let realmSystem=D.realmSystems[0],realmIndex=0;
function renderRealmSystem(id){realmSystem=D.realmSystems.find(x=>x.id===id);realmIndex=0;$$('[data-realm-system]').forEach(x=>x.classList.toggle('active',x.dataset.realmSystem===id));$('#realmPath').innerHTML=`<div class="realm-system-note"><div class="eyebrow">${realmSystem.name}</div><p>${realmSystem.subtitle}</p><div class="ascent-key"><span>↓ LOWEST / CHthonic</span><span>HIGHEST / CELESTIAL ↑</span></div></div>${realmSystem.realms.map((r,i)=>`<button class="realm-step ${i?'':'active'}" data-ri="${i}"><span>${String(i+1).padStart(2,'0')}</span><strong>${r.name}</strong><em>${i===0?'LOWEST':i===realmSystem.realms.length-1?'HIGHEST':'↑'}</em></button>`).join('')}<p class="realm-caution">${realmSystem.orderingNote||realmSystem.note}</p>`;$$('.realm-step').forEach(x=>x.onclick=()=>renderRealm(Number(x.dataset.ri)));renderRealm(0)}
function renderRealm(i){realmIndex=i;$$('.realm-step').forEach((x,j)=>x.classList.toggle('active',j===i));const r=realmSystem.realms[i],a=art(r.artworkId);$('#realmViewer').innerHTML=`<div class="realm-image">${imageMarkup(a,'realm-img',a.title)}<div class="art-credit">${credit(a)}</div></div><div class="realm-copy"><div class="mode-badge" data-mode="${a.mode}">${modeLabel(a.mode)}</div><div class="eyebrow">${realmSystem.name}</div><h3>${r.name}</h3><p>${r.text}</p><div class="art-note">${a.note}</div><a class="source-link" href="${a.source}" target="_blank" rel="noopener">Artwork source & rights ↗</a></div>`;bindFallbacks($('#realmViewer'))}
$$('[data-realm-system]').forEach(x=>x.onclick=()=>renderRealmSystem(x.dataset.realmSystem));renderRealmSystem('hindu');

// celestial
function renderPlanet(key){const p=D.planets[key],a=art(D.planetArtwork[key]);$$('.planet').forEach(x=>x.classList.toggle('active',x.dataset.planet===key));$('#planetGlyph').textContent=p.glyph;$('#planetTitle').textContent=p.label;$('#planetTheme').textContent=p.theme;$('#planetIntro').textContent=p.intro;$('#parallelList').innerHTML=p.links.map(x=>`<div class="parallel-item"><strong>${x.name}</strong><span>${x.tradition}<br>${x.relation}</span><em>${x.confidence}</em></div>`).join('');$('#celestialArt').innerHTML=`${imageMarkup(a,'celestial-img',a.title)}<div class="art-credit">${credit(a)}</div><div class="celestial-art-note"><span class="mode-badge" data-mode="${a.mode}">${modeLabel(a.mode)}</span><p>${a.note}</p><a href="${a.source}" target="_blank" rel="noopener">Source ↗</a></div>`;bindFallbacks($('#celestialArt'))}
$$('.planet').forEach(x=>x.onclick=()=>renderPlanet(x.dataset.planet));renderPlanet('venus');

// Grand Index
let filter='all',limit=16;const drawer=$('#indexDrawer'),search=$('#searchInput');$('#toggleIndex').onclick=()=>{drawer.hidden=!drawer.hidden;$('#toggleIndex').textContent=drawer.hidden?'Open the full index':'Close the full index';if(!drawer.hidden)renderIndex()};
const filters=[['all','All 84'],...D.traditions.map(t=>[t.id,t.name.split(' Worlds')[0]]),['water','Water'],['celestial','Celestial'],['underworld','Underworld'],['shapeshifter','Shapeshifters']];$('#filterRow').innerHTML=filters.map(([id,label],i)=>`<button class="filter-btn ${i?'':'active'}" data-filter="${id}">${label}</button>`).join('');$$('.filter-btn').forEach(x=>x.onclick=()=>{filter=x.dataset.filter;limit=16;$$('.filter-btn').forEach(y=>y.classList.toggle('active',y===x));renderIndex()});search.oninput=()=>{limit=16;renderIndex()};$('#showMore').onclick=()=>{limit+=16;renderIndex()};
function filtered(){const q=search.value.trim().toLowerCase();return D.beings.filter(b=>{const ok=filter==='all'||b.cluster===filter||b.tags.includes(filter),hay=[b.name,b.tradition,b.region,b.kind,b.summary,...b.tags].join(' ').toLowerCase();return ok&&(!q||hay.includes(q))})}
function renderIndex(){const all=filtered(),shown=all.slice(0,limit);$('#indexCount').textContent=`Showing ${shown.length} of ${all.length} matching · ${D.beings.length} total`;$('#beingGrid').innerHTML=shown.map(entityTile).join('');bindFallbacks($('#beingGrid'));$$('[data-being]',$('#beingGrid')).forEach(x=>x.onclick=()=>openEntity(x.dataset.being));$('#showMore').style.display=shown.length<all.length?'inline-flex':'none'}

// artwork ledger
const uniqueEntityArt=new Set(D.beings.map(b=>b.artworkId)).size;const realmCount=D.realmSystems.reduce((n,s)=>n+s.realms.length,0);$('#ledgerSummary').innerHTML=`<div><strong>${uniqueEntityArt}</strong><span>distinct entity art assignments</span></div><div><strong>${realmCount}</strong><span>illustrated realm stops</span></div><div><strong>${Object.keys(D.planetArtwork).length}</strong><span>celestial artworks</span></div><div><strong>${Object.keys(D.artworks).length}</strong><span>artwork records in ledger</span></div>`;
$('#toggleLedger').onclick=()=>{const g=$('#creditsGrid');g.hidden=!g.hidden;$('#toggleLedger').textContent=g.hidden?'Open the complete artwork ledger':'Close the artwork ledger';if(!g.hidden&&!g.dataset.rendered){g.dataset.rendered='1';g.innerHTML=Object.values(D.artworks).map(a=>`<article class="credit-card"><div class="credit-thumb">${imageMarkup(a,'credit-img',a.title)}<span class="mode-mini">${modeLabel(a.mode)}</span></div><div class="credit-copy"><strong>${a.title}</strong><p>${a.artist} · ${a.date}<br>${a.collection}</p><div class="credit-meta"><span>${a.license}</span></div><small>${a.note}</small><a href="${a.source}" target="_blank" rel="noopener">Source & rights ↗</a></div></article>`).join('');bindFallbacks(g)}};
})();